###############################################################################
# THIS SAMPLE PROGRAM IS PROVIDED AS IS. THE SAMPLE PROGRAM AND ANY RESULTS   #
# OBTAINED FROM IT ARE PROVIDED WITHOUT ANY WARRANTIES OR REPRESENTATIONS,    #
# EXPRESS, IMPLIED OR STATUTORY.                                              #
###############################################################################
# Makefile for building: SBCAP_MME
# Generated by ASN.1 Studio 10.4
###############################################################################
	
OSSASN1 = /home/lacerda/asn1cpp/linux-x86-64/7.2.0
COMMONMAK = $(OSSASN1)/samples/common.mak

ifneq ("$(wildcard $(COMMONMAK))","")
include $(OSSASN1)/samples/common.mak
else
$(error The OSS configuration file '$(COMMONMAK)' is not found. To run the \
generated makefile, please change the OSSASN1 macro to the location of the OSS ASN.1 Tools)
endif
    
TARGET     = SBCAP_MME
ASN1       = $(OSSASN1)/bin/asn1cpp
CCOMP      = $(CXX)
OSSINC     = $(OSSASN1)/include
FLAGS      = $(CXXFLAGS) -I$(OSSINC)  $(SHARED) -DOSSDEBUG=7 -DOSSPRINT -I.
LINK       = $(LDXX)
LFLAGS     = $(LDFLAGS) 
OSSLIBS    = $(OSSLIB)/libosscpp.sa \
	$(OSSLIB)/libcpptoed.sa
GENHEADERS = sbcap.h
GENFILES   = sbcap.cpp $(GENHEADERS)
DELGENFILES =
OBJECTS    = sbcap.o \
	General_func.o \
	Principal.o \
	Sbc_func.o \
	Sctp_func.o
CMDFILE    = SBCAP_MME.cmd
ASN1FILES  = ../../../../asn1studio/linux-x86-64bit/Asn1Standards/3GPP/29-series/SBCAP/v16.0.0/sbcap.asn
USERHEADERS = General_func.h \
	Principal.h \
	Sbc_func.h \
	Sctp_func.h
ARGS       = 
TARGETS    = $(TARGET) $(TARGET).out

all: $(TARGET).out
	-$(MORE) $?

$(TARGET).out: $(TARGET)
	-./$? $(ARGS) >$@ || true
#
# Link the C/C++-compiled output with the OSS runtime library.
#
$(TARGET): $(OBJECTS) $(OSSLIBS)
	$(LINK) $(LFLAGS) -o $@ $(OBJECTS) $(OSSLIBS) $(LIBS)
	$(STRIP) $@
	
#
# C/C++-compile the output of the ASN.1 compiler and optional user files.
#
sbcap.o: sbcap.cpp $(GENFILES) 
	$(CCOMP) $(FLAGS) -c sbcap.cpp
General_func.o: General_func.cpp $(GENFILES) $(USERHEADERS)
	$(CCOMP) $(FLAGS) -c General_func.cpp
Principal.o: Principal.cpp $(GENFILES) $(USERHEADERS)
	$(CCOMP) $(FLAGS) -c Principal.cpp
Sbc_func.o: Sbc_func.cpp $(GENFILES) $(USERHEADERS)
	$(CCOMP) $(FLAGS) -c Sbc_func.cpp
Sctp_func.o: Sctp_func.cpp $(GENFILES) $(USERHEADERS)
	$(CCOMP) $(FLAGS) -c Sctp_func.cpp
#
# ASN.1-compile the input ASN.1 files and generate C/C++ code.
#
DELGENFILES = $(GENFILES)
$(GENFILES): $(ASN1FILES) $(CMDFILE)
	$(ASN1) -command $(CMDFILE)
    
#
# Run target: "make run" to execute the application
#
.PHONY : run
run:
	-./$(TARGET) $(ARGS)
    
#
# Clean up.
#
.PHONY : clean
clean:
	$(RM) $(DELGENFILES) $(OBJECTS) $(TARGETS)
    